[package]
name = "niri-visual-tests"
version.workspace = true
description.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
adw = { version = "0.8.1", package = "libadwaita", features = ["v1_4"] }
anyhow.workspace = true
gtk = { version = "0.10.3", package = "gtk4", features = ["v4_12"] }
niri = { version = "26.4.0", path = ".." }
niri-config = { version = "26.4.0", path = "../niri-config" }
png = "0.18.1"
smithay.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[[bin]]
name = "grid-move-headless"
path = "src/bin/grid_move_headless.rs"

[[bin]]
name = "grid-issues-headless"
path = "src/bin/grid_issues_headless.rs"

[[bin]]
name = "grid-minimized-headless"
path = "src/bin/grid_minimized_headless.rs"
