#[derive(Debug, Default, Clone, Copy, PartialEq)]
pub struct LiquidGlassOptions {
    pub refraction_strength: f64,
    pub power_factor: f64,
    pub refraction_a: f64,
    pub refraction_b: f64,
    pub refraction_c: f64,
    pub refraction_d: f64,
    pub refraction_power: f64,
    pub glow_weight: f64,
    pub glow_bias: f64,
    pub glow_edge0: f64,
    pub glow_edge1: f64,
    pub edge_lighting: f64,
    pub fringing: f64,
    pub refraction_dilute: f64,
    pub dilute_strength: f64,
    pub dilute_fringing: f64,
    pub physical_refraction: f64,
    pub lens_distortion: f64,
    pub brightness: f64,
    pub contrast: f64,
    pub saturation: f64,
    pub vibrancy: f64,
    pub adaptive_dim: f64,
    pub adaptive_boost: f64,
    pub edge_thickness: f64,
    pub edge_padding: f64,
}

impl From<niri_config::LiquidGlass> for LiquidGlassOptions {
    fn from(config: niri_config::LiquidGlass) -> Self {
        Self {
            refraction_strength: config.refraction_strength,
            power_factor: config.power_factor,
            refraction_a: config.refraction_a,
            refraction_b: config.refraction_b,
            refraction_c: config.refraction_c,
            refraction_d: config.refraction_d,
            refraction_power: config.refraction_power,
            glow_weight: config.glow_weight,
            glow_bias: config.glow_bias,
            glow_edge0: config.glow_edge0,
            glow_edge1: config.glow_edge1,
            edge_lighting: config.edge_lighting,
            fringing: config.fringing,
            refraction_dilute: config.refraction_dilute,
            dilute_strength: config.dilute_strength,
            dilute_fringing: config.dilute_fringing,
            physical_refraction: config.physical_refraction,
            lens_distortion: config.lens_distortion,
            brightness: config.brightness,
            contrast: config.contrast,
            saturation: config.saturation,
            vibrancy: config.vibrancy,
            adaptive_dim: config.adaptive_dim,
            adaptive_boost: config.adaptive_boost,
            edge_thickness: config.edge_thickness,
            edge_padding: config.edge_padding,
        }
    }
}
// force rebuild
